[Cuisinart_TOA-95.pdf]
original-filename = "P-TOA-95.pdf"
source = "https://images.salsify.com/images/pc5ab3r3akczrihnebn0/P-TOA-95.pdf"

[Cuisinart-Large-Digital-AirFryer-Toaster-Oven-TOA-95-UserManual.pdf]
original-filename = "Cuisinart-Large-Digital-AirFryer-Toaster-Oven-TOA-95-UserManual.pdf"
source = "https://www.williams-sonoma.com/netstorage/pdf/Cuisinart-Large-Digital-AirFryer-Toaster-Oven-TOA-95-UserManual.pdf"
